#!/usr/bin/env python3
"""Bake TrueType faces into src/font_data.h.

The renderer draws its own HUD text, so it needs glyph bitmaps compiled in.
This script rasterises an 8-bit alpha atlas per face with Pillow and emits a
base64 blob plus per-glyph metrics. The generated header is committed, so
building the project never needs Python or Pillow.

Usage: python3 tools/genfont.py
"""

import base64
import os
import sys

from PIL import Image, ImageFont

OUT = os.path.join(os.path.dirname(__file__), "..", "src", "font_data.h")

FACES = [
    ("UI",      "/usr/share/fonts/opentype/inter/Inter-Regular.otf",     15),
    ("UIBold",  "/usr/share/fonts/opentype/inter/Inter-SemiBold.otf",    15),
    ("Title",   "/usr/share/fonts/opentype/inter/Inter-Bold.otf",        23),
    ("Mono",    "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf",   13),
    ("MonoBold","/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf", 13),
]

# ASCII plus the handful of symbols the HUD actually uses.
CODEPOINTS = list(range(32, 127)) + [
    0x00B0,  # degree
    0x00B2,  # superscript two
    0x00B7,  # middle dot
    0x00D7,  # multiplication sign
    0x03B1,  # alpha
    0x03B2,  # beta
    0x03A3,  # Sigma
    0x03C0,  # pi
    0x03C7,  # chi
    0x2013,  # en dash
    0x2192,  # right arrow
    0x2212,  # minus sign
    0x2248,  # almost equal
    0x2264,  # <=
    0x2265,  # >=
]


def bake(path, size):
    font = ImageFont.truetype(path, size)
    ascent, descent = font.getmetrics()
    glyphs = []
    blob = bytearray()
    for cp in CODEPOINTS:
        ch = chr(cp)
        mask = font.getmask(ch, mode="L")
        w, h = mask.size
        bbox = font.getbbox(ch, anchor="ls")  # relative to the left baseline
        bx, by = (bbox[0], bbox[1]) if bbox else (0, 0)
        adv = font.getlength(ch)
        offset = len(blob)
        if w and h:
            blob += bytes(Image.frombytes("L", (w, h), bytes(mask)).tobytes())
        glyphs.append((cp, w, h, bx, by, adv, offset))
    return {
        "ascent": ascent,
        "descent": descent,
        "line": ascent + descent,
        "glyphs": glyphs,
        "blob": bytes(blob),
    }


def main():
    faces = []
    for name, path, size in FACES:
        if not os.path.exists(path):
            sys.exit("missing font: " + path)
        faces.append((name, path, size, bake(path, size)))

    lines = []
    lines.append("// font_data.h - GENERATED by tools/genfont.py. Do not edit by hand.")
    lines.append("//")
    lines.append("// 8-bit alpha glyph atlases so the renderer can draw HUD text without")
    lines.append("// linking a font library. Regenerate with: python3 tools/genfont.py")
    lines.append("#pragma once")
    lines.append("")
    lines.append("namespace sl {")
    lines.append("namespace fontdata {")
    lines.append("")
    lines.append("struct GlyphRec {")
    lines.append("    int cp, w, h, bearingX, bearingY, offset;")
    lines.append("    float advance;")
    lines.append("};")
    lines.append("")
    lines.append("struct FaceRec {")
    lines.append("    const char* name;")
    lines.append("    int pixelSize, ascent, descent, lineHeight, glyphCount;")
    lines.append("    const GlyphRec* glyphs;")
    lines.append("    const char* blobBase64;")
    lines.append("    int blobBytes;")
    lines.append("};")
    lines.append("")

    for name, path, size, f in faces:
        lines.append("// %s - %s @ %dpx" % (name, os.path.basename(path), size))
        lines.append("static const GlyphRec k%sGlyphs[] = {" % name)
        for cp, w, h, bx, by, adv, off in f["glyphs"]:
            lines.append("    {%d,%d,%d,%d,%d,%d,%.4ff}," % (cp, w, h, bx, by, off, adv))
        lines.append("};")
        b64 = base64.b64encode(f["blob"]).decode("ascii")
        lines.append("static const char k%sBlob[] =" % name)
        for i in range(0, len(b64), 100):
            lines.append('    "%s"' % b64[i:i + 100])
        lines.append("    ;")
        lines.append("")

    lines.append("static const FaceRec kFaces[] = {")
    for name, path, size, f in faces:
        lines.append(
            '    {"%s", %d, %d, %d, %d, %d, k%sGlyphs, k%sBlob, %d},'
            % (name, size, f["ascent"], f["descent"], f["line"],
               len(f["glyphs"]), name, name, len(f["blob"])))
    lines.append("};")
    lines.append("static const int kFaceCount = %d;" % len(faces))
    lines.append("")
    lines.append("}  // namespace fontdata")
    lines.append("}  // namespace sl")
    lines.append("")

    with open(os.path.abspath(OUT), "w") as fh:
        fh.write("\n".join(lines))

    total = sum(len(f["blob"]) for _, _, _, f in faces)
    print("wrote %s (%d faces, %d glyphs each, %d atlas bytes)"
          % (os.path.abspath(OUT), len(faces), len(CODEPOINTS), total))


if __name__ == "__main__":
    main()
